[package]
name = "jimmer"
version = "0.1.0"
edition = "2021"

[dependencies]
clearscreen = "4.0.1"
colored = "3.0.0"
crossterm = "0.28.1"
rand = "0.9.0"
rodio = "0.20.1"
tui = "0.19.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"